{
  "language": "java",
  "os": [
    "linux"
  ],
  "dist": "trusty",
  "jdk": [
    "oraclejdk8"
  ],
  "sudo": true,
  "services": [
    "docker"
  ],
  "before_install": [
    "cd docker/dev",
    "docker-compose up -d",
    "docker ps -a"
  ],
  "before_script": [
    "cd ../../src/"
  ],
  "script": [
    "mvn test",
    "mvn test -Ptest-consumer",
    "mvn test -Ptest-business"
  ]
}