language: java
sudo: false

addons:
  sonarcloud:
    organization: "benzouille"
    token:
      secure: "174dce8197571a8613438612cfb2527a395f33d8" # encrypted value of your token

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar